<?php
/* Autogenerated Forum Controller */
/* Hook point of the Forum package inside your laravel application */
/* Feel free to override methods here to fit your requirements */
class ForumController extends \Atrakeur\Forum\Controllers\AbstractViewForumController {

}
